site_name: "Premier projet python"
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  highlightjs: true
  hljs_languages:
    - markdown
    - python
nav:
  - Accueil: index.md
  - Getting started: getting-started.md
  - About Python:
      - Version: about-python/version.md
      - Install dependence: about-python/dependence.md
      - Virtual environment: about-python/venv.md
      - Build project: about-python/build.md
  - Utility scripts: utility-scripts.md
  - Other: other.md
  - API:
      - Example: api/example.md
